### ISSUE TITLE
code reviewing

### ISSUE THREAD

**Issue by RedJocker** [Marcell-Juhasz/secret-diary#1]
Hi I was assigned to make a code review for the project, specially tests, and I haven't looked it yet but certainly there will be some things to be fixed so I would like to know if it is ok if we create a work flow in which I report the issues that I find  opening threads for them here so we can work together to improve the project. Is that ok for you?

**Comment by Marcell-Juhasz** [comment]
Hi! That's fine, it's ok for me

**Comment by RedJocker** [comment]
cool

**Comment by Marcell-Juhasz** [comment]
I have made the changes you have suggested and updated the project on github
