### ISSUE TITLE
change activity: MainActivity to activity: Activity

### ISSUE THREAD

**Issue by RedJocker** [Marcell-Juhasz/secret-diary#12]
We should be thinking about black box testing, using more generic Activity as type instead of MainActivity, prevents us from assuming implementations of properties/methods from the MainActivity. 
I haven't seen any direct use MainActivity properties/methods on tests, which is good, but we should assume that in the future maybe someone that does not know what is doing is assigned to fix tests and we should prevent this hypothetical person from doing the wrong thing.

**Comment by Marcell-Juhasz** [comment]
done
