### ISSUE TITLE
stage5 description use ordered list if you want to enumerate items on description

### ISSUE THREAD

**Issue by RedJocker** [Marcell-Juhasz/secret-diary#24]
instead of 

```
<p>1. Create a new ....

<ul>
    <li>...</li>
    <li>...</li>
    ...
</ul>

<p>2. If the user presses ...</p>
```

use ordered  list, you can have nested lists no problem

```
<ol>
  <li> Create a new ....

    <ul>
      <li>...</li>
      <li>...</li>
      ...
     </ul>
  </li>
  
  <li> If the user presses ... </li>

```

**Comment by Marcell-Juhasz** [comment]
Fixed: #69b6832

**Comment by RedJocker** [comment]
to reference a commit you can click on "copy the full SHA", the icon is two squares one above the other. then paste the SHA here. It is easier to reference the issue number on the commit message.

commit 69b6832535ea69ff75f5a4d7dd0437c67401aaab

**Comment by RedJocker** [comment]
you have commited on the main branch, but other modifications are being commited on stepik branch. I. think you should make all commits on stepik branch so that we don't get confused later. 

to upload the project back to stepik I will have to download the current version and copy the content from here to the downloaded version and then upload. So don't worry about having a branch without the solution, I will handle that on the upload by only copying the necessary files.

**Comment by Marcell-Juhasz** [comment]
> you have commited on the main branch, but other modifications are being commited on stepik branch. I. think you should make all commits on stepik branch so that we don't get confused later.

I wanted to edit the files on the stepik branch as I did with the previous commit, but on the stepik branch there were no task.html files, that is why I edited them on the main.

**Comment by RedJocker** [comment]
yes there are,  just inside the stage folder. But it doesn't have to be that branch, just keep all modifications on same branch, and somewhere I can run tests against a solution. I was looking at stepik again and there is no solution there so probably it is better somewhere else

**Comment by Marcell-Juhasz** [comment]
Committed to solution: 1145120c88da234170fd2c4e948e3fa024964d3c

**Comment by RedJocker** [comment]
it is better, but you deleted this sentence

```
<p>Obs: Tests assume the existence of LoginActivity class. Build will fail if that class has not been created yet.</p>
```

Ideally tests should not cause build failure, but in case they do users should be warned about it.

I will close this issue and open a new about the warning
