### ISSUE TITLE
gradle files

### ISSUE THREAD

**Issue by RedJocker** [Marcell-Juhasz/secret-diary#3]
we have a new template for gradle files that should be used for every project

https://github.com/hyperskill/android-projects-template

copy gradle related files from this repository
- settings.gradle
- gradle.properties
- build.gradle (root)
- build.gradle (module)

don't forget to add the dependecies that are specific to this project 

also copy .gitignore and delete build-src and documents.

finally you should delete from repository:
- gradlew
- gradlew.bat
- gradle/wrapper

**Comment by Marcell-Juhasz** [comment]
Done
