### ISSUE TITLE
prefer using shadowLooper.idleFor() instead of shadowLooper.runToEndOfTasks()

### ISSUE THREAD

**Issue by RedJocker** [Marcell-Juhasz/secret-diary#9]
Since your application is sensitive to the current time state it is better to have a better control of elapsed time. Prefer using .idleFor() instead of .runToEndOfTasks() whenever possible.

**Comment by Marcell-Juhasz** [comment]
In most of the cases (except the one when I want to wait 3 seconds) I only need to wait for the changes to be performed after a button click and I do not know how much time it takes for example for an AlertDialog to be shown. I saw that you have written a method: fun View.clickAndRun(millis: Long = 500). But how can you be sure if the AlertDialog will be loaded in 500 ms after the button click?

**Comment by RedJocker** [comment]
On what I can understand the ShadowLooper will advance the clock and run every runnable that was scheduled to run in that timeframe.  The code is going to run unless there is some asynchronous code, like using post, that is scheduling the runnable for later than 500 millis. 
I think you can leave the default, but you are checking some timestamps aren't you? It is probably a good idea to test if the timestamp is being done correctly. An user might try to implement the timestamps manually and have mistakes like 01:60 instead of 02:00. In this case you will want to know how much time is passing from one point of your test code to another.

**Comment by RedJocker** [comment]
If you really don't care about time for a particular test then it can be ok to use runToEndOfTasks, but here the clock will advance as much as the time of the last scheduled task, which will be out of your control

**Comment by Marcell-Juhasz** [comment]
I think I understood how time handling works, thanks.

**Comment by Marcell-Juhasz** [comment]
done
